# Configuration for gradient sanity check

# Use with: python src/run.py --config configs/report/2blob/sim/low_res.yaml

cuda_visible_devices: '0'

mode : sim  # Experiment mode (options: "sim", "sampling", "mle", "grid")

# --- PLOT & VIDEO SETTINGS ---
plot_settings:
  enable_energy_tracking: true  # Calculate and plot energy evolution
  density_field_plot: 
    do: true  # Plot density field
  trajectories_plot: 
    do: true  # Plot particle trajectories
    num_trajectories: 5     # Number of particle trajectories to plot
    zoom_for_trajectories: true  # Zoom in on trajectories
  timeseries_plot: 
    do: true  # Plot time series of particle positions
    n_timesteps: 50        # Number of timesteps to plot
  velocity_plot: 
    do: true  
  generate_video: 
    do: false  # Generate video of the simulation
    video_fps: 30            # Video frames per second
    video_dpi: 200           # Video resolution DPI
  units:
    kpc_per_pixel: 6.25
    msun_per_mass_unit: 1.35e+7
    gyr_per_time_unit: 2.0
    jouleE50_per_unit : 2.54e-6

# --- FORWARD MODEL PARAMETERS ---
model_params:  
  # General parameters
  G: 1              # Gravitational constant
  length: 32          # Box size
  softening: 1      # Softening length
  t_f: 2.0            # Final time
  dt: 0.001            # Time step
  data_seed: 42       # Random seed for data generation
  solver: "LeapfrogMidpoint" # Solver type: "LeapfrogMidpoint", "Dopri5", "Dopri8", "Tsit5", "Heun, "Midpoint"
  
  # Density field scaling options
  density_scaling: "log"  # Options: "none", "log", "sqrt", "power", "asinh", "signed_log"
  velocity_scaling: "signed_log"  # Options: "none", "log", "sqrt", "power", "asinh", "signed_log"
  
  # Blob parameters - a list of blob configurations for generating mock data
  blobs_params:
    # Blob 1: Gaussian at corner 1 of triangle
      - n_part: 1500
        m_part: 0.49
        pos_type: gaussian
        pos_params:
          sigma: 1.6  
          center: 12  # Scaled from 48
        vel_type: circular
        vel_params:
          vel_factor: 0.1
          vel_dispersion: 0.05
          distrib: True
        # Blob 2: Gaussian at corner 2 of triangle
      - n_part: 1500
        m_part: 0.99
        pos_type: gaussian
        pos_params:
          sigma: 2.4  
          center: 20  # Scaled from 80
        vel_type: circular
        vel_params:
          vel_factor: 0.1 
          vel_dispersion: 0.05
          distrib: True