# Configuration for N-body simulation using blobs model

# --- HARDWARE/CLUSTER SETTINGS ---
cuda_visible_devices: 4  # GPU index to use

# --- EXPERIMENT MODE and MISCELLANEOUS ---
mode: sim      # Experiment mode (options: "sim", "sampling")

# --- PLOT & VIDEO SETTINGS ---
plot_settings:
  enable_energy_tracking: false  # Calculate and plot energy evolution
  density_field_plot: 
    do: true  # Plot density field
  trajectories_plot: 
    do: true  # Plot particle trajectories
    num_trajectories: 10     # Number of particle trajectories to plot
    zoom_for_trajectories: true  # Zoom in on trajectories
  timeseries_plot: 
    do: true  # Plot time series of particle positions
    n_timesteps: 8        # Number of timesteps to plot
  velocity_plot: 
    do: true  
  generate_video: 
    do: false  # Generate video of the simulation
    video_fps: 30            # Video frames per second
    video_dpi: 200           # Video resolution DPI

# --- FORWARD MODEL PARAMETERS ---
model_params:  
  # General parameters
  G: 5.0              # Gravitational constant
  length: 64          # Box size
  softening: 0.1      # Softening length
  t_f: 0.75            # Final time
  dt: 0.05            # Time step
  data_seed: 42       # Random seed for data generation
  solver: "LeapfrogMidpoint"  # Solver type: "LeapfrogMidpoint", "Dopri5", "Dopri8", "Tsit5"
  
  # Density field scaling options
  density_scaling: "normalize"  # Options: "none", "log", "sqrt", "normalize", "standardize", "power"
  scaling_kwargs:
    log_offset: 1.0e-8  # Offset for log scaling
  
  # Blob parameters - a list of blob configurations
  blobs_params:
    # Blob 1: Gaussian with circular velocities (heavy particles)
      - n_part: 1000
        m_part: 2.0  # Heavy particles
        pos_type: gaussian
        pos_params:
          sigma: 8.0
          center: [12.0, 52.0, 12.0]
        vel_type: circular
        vel_params:
          vel_factor: 1.0  # Multiplier for circular velocity
          distrib: False # Use circular velocity distribution or proxy

      # Blob 2: NFW with virial velocities (medium particles)
      - n_part: 1000
        m_part: 1.0  # Standard mass
        pos_type: nfw
        pos_params:
          rs: 5.0          # Scale radius
          c: 2.0           # Concentration parameter
          center: [12.0, 12.0, 52.0]
        vel_type: virial
        vel_params:
          virial_ratio: 0.5  # Sub-virial (cold) initial condition

      # Blob 3: Gaussian with cold velocities (light particles)
      - n_part: 1000
        m_part: 0.5  # Light particles
        pos_type: gaussian
        pos_params:
          sigma: 6.0
          center: [52.0, 12.0, 12.0]
        vel_type: cold
        vel_params:
          vel_dispersion: 0.1  # Small random velocities
          
      # Blob 4: Plummer sphere (heavy particles)
      - n_part: 1000
        m_part: 3.0  # Very heavy particles
        pos_type: plummer
        pos_params:
          rs: 5.0  # Plummer radius
          center: [32.0, 32.0, 32.0]
        vel_type: circular
        vel_params:
          vel_factor: 1.0
          distrib: true  # Use distribution-specific circular velocities

# --- SAMPLING CONFIGURATION (only used when mode: sampling) ---
sampler: "nuts"           # Sampler type: "nuts", "hmc", "rwm", "mala"
num_chains: 4             # Total number of chains across all MPI processes
num_samples: 1000         # Samples per chain
num_warmup: 1000          # Warmup samples per chain
sampling_seed: 12345      # Random seed for sampling

# MPI configuration
mpi_gpu_devices: [0, 1, 2, 3]  # List of GPU devices to use, or "0,1,2,3"
rhat_check_interval: 100       # Check R-hat every N samples

# Initial positions for sampling
initial_position:
  blob0_sigma: 8.0
  blob0_center: [32.0, 32.0, 32.0]
  blob1_rs: 5.0
  blob1_c: 2.0
  blob1_center: [32.0, 32.0, 32.0]

# Prior configuration
prior_type: "blob_gaussian"
prior_params:
  blob0_sigma:
    mu: 8.0
    sigma: 2.0
  blob0_center:
    mu: [32.0, 32.0, 32.0]
    sigma: 5.0
  blob1_rs:
    mu: 5.0
    sigma: 1.0
  blob1_c:
    mu: 2.0
    sigma: 0.5
  blob1_center:
    mu: [32.0, 32.0, 32.0]
    sigma: 5.0

# Likelihood configuration
likelihood_type: "ll1"
likelihood_kwargs:
  noise: 0.1

