# Configuration for N-body parameter inference using blobs model

# Use with : python src/run_experiments.py --config configs/default_sampling_hmc.yaml

# --- HARDWARE/CLUSTER SETTINGS ---
cuda_visible_devices: 1  # GPU index to use

# --- EXPERIMENT MODE and MISCELLANEOUS ---
mode: sampling      # Experiment mode (options: "sim", "sampling")

# --- PLOT & VIDEO SETTINGS ---
plot_settings:
  enable_energy_tracking: true  # Calculate and plot energy evolution
  density_field_plot: 
    do: true  # Plot density field
  trajectories_plot: 
    do: true  # Plot particle trajectories
    num_trajectories: 10     # Number of particle trajectories to plot
    zoom_for_trajectories: true  # Zoom in on trajectories
  timeseries_plot: 
    do: true  # Plot time series of particle positions
    n_timesteps: 8        # Number of timesteps to plot
  velocity_plot: 
    do: true  
  generate_video: 
    do: false  # Generate video of the simulation
    video_fps: 30            # Video frames per second
    video_dpi: 200           # Video resolution DPI

# --- FORWARD MODEL PARAMETERS ---
model_params:  
  # General parameters
  G: 5.0              # Gravitational constant
  length: 64          # Box size
  softening: 1      # Softening length
  t_f: 1.0            # Final time (shorter for sampling)
  dt: 0.05            # Time step
  m_part: 1.0         # Particle mass
  data_seed: 42       # Random seed for data generation
  solver: "LeapfrogMidpoint"  # Solver type: "LeapfrogMidpoint", "Dopri5", "Dopri8", "Tsit5"
  
  
  # Density field scaling options
  density_scaling: "normalize"  # Options: "none", "log", "sqrt", "normalize", "standardize", "power"
  scaling_kwargs:
    log_offset: 1.0e-8  # Offset for log scaling
  
  # Blob parameters - a list of blob configurations for generating mock data
  blobs_params:
    # Single Gaussian blob with circular velocities for simplicity
    - n_part: 2000
      pos_type: gaussian
      pos_params:
        sigma: 10.0  
        center: [32.0, 32.0, 32.0] 
      vel_type: circular
      vel_params:
        vel_factor: 0.5  
        distrib: True

# --- LIKELIHOOD SETTINGS ---
likelihood_type: ll1   # Options: "ll1", "ll2"
likelihood_kwargs: 
  noise: 1  # Standard deviation of instrumental noise
  # For ll2 only:
  # n_realizations: 10    # Number of model realizations to average over
  # parallel_ll2: false   # Whether to parallelize ll2 evaluations using pmap

# Parallel likelihood options (only for ll2):
# parallel_ll2: true      # Use pmap to parallelize likelihood evaluations
                          # Note: Only effective with likelihood_type: ll2
                          # Automatically splits n_realizations across available devices

# --- PRIOR SETTINGS ---
prior_type: blob_gaussian  # Use blob-specific prior
prior_params:
  # Priors for the parameters we want to infer
  blob0_sigma: {mu: 10.0, sigma: 5.0}
  blob0_center: {mu: [32.0, 32.0, 32.0], sigma: 10.0}
  #blob0_vel_factor: {mu: 0.3, sigma: 0.3} #REMOVE A PRIOR TO NOT SAMPLE A PARAM

# --- SAMPLER SETTINGS ---
sampler: hmc            # Hamiltonian Monte Carlo sampler
num_samples: 2000       # Number of MCMC samples to draw
sampling_seed: 12345    # Random seed for reproducibility
progress_bar: false      # Show progress bar during sampling

# Parallel sampling options:
n_chains: 1             # Number of parallel chains (1 = single chain, >1 = parallel chains)
                        # Note: Requires n_chains <= number of available GPUs/devices for optimal performance

# HMC-specific parameters:
step_size: 0.02         # Step size for leapfrog integrator
num_integration_steps: 40  # Number of leapfrog steps per HMC proposal

# Mass matrix options:
# Option 1: Diagonal mass matrix (list of diagonal elements)
inv_mass_matrix: [1, 0.04, 100.0]  # Will be automatically adjusted based on parameters

# Option 2: Identity mass matrix
# inv_mass_matrix: 1.0    # Single value for identity matrix

# Option 3: Full mass matrix (if correlation between parameters is known)
# inv_mass_matrix: [[1.0, 0.1], [0.1, 0.04]]  # 2x2 example for correlated parameters

# HMC tuning guidelines:
# - step_size * num_integration_steps should be roughly O(1)
# - Larger step_size allows faster exploration but may reduce acceptance rate
# - More integration steps improve proposal quality but increase computational cost
# - Mass matrix should reflect parameter scales (smaller values for larger-scale parameters)

# Initial position for the sampler - start with values different from the true ones
initial_position: 
  blob0_sigma: 10.0          # Starting guess for sigma
  blob0_center: [32.0, 32.0, 32.0]  # Starting guess for center
  #blob0_vel_factor: 0.3     # Starting guess for velocity factor
