# Configuration for gradient sanity check

# Use with: python src/run.py --config configs/stable_configs/dwarf_galaxy/grid.yaml

cuda_visible_devices: '4'

mode : grid  # Experiment mode (options: "sim", "sampling", "mle", "grid")

# --- PLOT & VIDEO SETTINGS ---
plot_settings:
  enable_energy_tracking: false  # Calculate and plot energy evolution
  density_field_plot: 
    do: false  # Plot density field
  trajectories_plot: 
    do: false  # Plot particle trajectories
    num_trajectories: 10     # Number of particle trajectories to plot
    zoom_for_trajectories: false  # Zoom in on trajectories
  timeseries_plot: 
    do: false  # Plot time series of particle positions
    n_timesteps: 8        # Number of timesteps to plot
  velocity_plot: 
    do: false  
  generate_video: 
    do: false  # Generate video of the simulation
    video_fps: 30            # Video frames per second
    video_dpi: 200           # Video resolution DPI


# --- FORWARD MODEL PARAMETERS ---
model_params:  
  # General parameters
  G: 1              # Gravitational constant
  length: 64          # Box size
  softening: 1      # Softening length
  t_f: 2.0            # Final time
  dt: 0.1            # Time step
  data_seed: 42       # Random seed for data generation
  solver: "LeapfrogMidpoint" # Solver type: "LeapfrogMidpoint", "Dopri5", "Dopri8", "Tsit5", "Heun, "Midpoint"
  
  # Density field scaling options
  density_scaling: "log"  # Options: "none", "log", "sqrt", "power", "asinh", "signed_log"
  velocity_scaling: "none"  # Options: "none", "log", "sqrt", "power", "asinh", "signed_log"
  
  # Blob parameters - a list of blob configurations for generating mock data
  blobs_params:
    # Blob 1: Gaussian at corner 1 of triangle
      - n_part: 1500
        m_part: 6
        pos_type: gaussian
        pos_params:
          sigma: 6.4  
          center: 20
        vel_type: circular
        vel_params:
          vel_factor: 0.05
          distrib: True
        # Blob 2: Gaussian at corner 2 of triangle
      - n_part: 1500
        m_part: 12
        pos_type: gaussian
        pos_params:
          sigma: 9.6  
          center: 38
        vel_type: circular
        vel_params:
          vel_factor: 0.05 
          distrib: True

# --- HYPERCUBE PARAMETERS ---
hypercube_params:
  n_points_per_dim: 15   # Number of points per parameter dimension 
  mini_batch_size_value: 30 # Size of mini-batches for value evaluation 
  mini_batch_size_grad: 5 # Size of mini-batches for gradient evaluation 
  
  # Parameter bounds for the hypercube
  param_bounds: # Bounds will be the same for each blob
    blob0_sigma: 
      min: 4.0
      max: 12.0
    blob0_center:
      min: 17.5
      max: 40.5
    blob1_sigma: 
      min: 4.0
      max: 12.0
    blob1_center:
      min: 17.5
      max: 40.5
    

# --- LIKELIHOOD SETTINGS ---
likelihood_type: ll1   # Options: "ll1", "ll2"
likelihood_kwargs: 
  noise: 1  # Standard deviation of instrumental noise

# --- PRIOR SETTINGS ---
prior_type: blob_uniform  # Use blob-specific prior
prior_params:
  # Priors for the parameters we want to infer
  blob0_sigma: {low: 3.5, high: 12.5}
  blob0_center: {low: 17.5, high: 40.5}
  blob1_sigma: {low: 3.5, high: 12.5}
  blob1_center: {low: 17.5, high: 40.5}
