# Configuration file for corner plots analysis
# Use with: python src/sampling_plots.py configs/analysis/analysis_config.yaml
# List of directories containing MCMC samples
directories:
    - results/sampling_results/rwm_init2_20250815_203323 
    - results/sampling_results/rwm_init3_20250815_203207 
    - results/sampling_results/rwm_init4_20250815_203052
    - results/sampling_results/rwm_init1_20250815_203438



output_dir: "results/corner_plots"

# Number of burn-in samples to discard (optional, can be overridden by command line)
burnin: 0

# Analysis parameters
analysis:
    # Interval for computing R-hat and ESS (every N samples)
    n_samples_interval: 10

# Optional: Add description for documentation
description: "Analysis of RWM sampling results from August 14, 2025"
