# Configuration for N-body parameter inference using blobs model

# python src/run_experiments.py --config configs/sampling/test_sampling_2blobs.yaml
# mpiexec -n 7 python src/run_experiments.py --config configs/config_twoblobs.yaml
# --- HARDWARE/CLUSTER SETTINGS ---
mpi_gpu_devices: [0, 1, 3, 4, 5, 6, 7] 

# --- EXPERIMENT MODE ---
mode: sampling      # Experiment mode (options: "sim", "sampling")

# --- PLOT & VIDEO SETTINGS ---
plot_settings:
  enable_energy_tracking: true  # Calculate and plot energy evolution
  density_field_plot: 
    do: true  # Plot density field
  trajectories_plot: 
    do: true  # Plot particle trajectories
    num_trajectories: 5     # Number of particle trajectories to plot
    zoom_for_trajectories: true  # Zoom in on trajectories
  timeseries_plot: 
    do: true  # Plot time series of particle positions
    n_timesteps: 8        # Number of timesteps to plot
  velocity_plot: 
    do: true  
  generate_video: 
    do: false  # Generate video of the simulation
    video_fps: 30            # Video frames per second
    video_dpi: 200           # Video resolution DPI

# --- FORWARD MODEL PARAMETERS ---
model_params:  
  # General parameters
  G: 10.0              # Gravitational constant
  length: 64          # Box size
  softening: 1      # Softening length
  t_f: 0.35            # Final time
  dt: 0.01            # Time step
  data_seed: 42       # Random seed for data generation
  solver: "Tsit5" # Solver type: "LeapfrogMidpoint", "Dopri5", "Dopri8", "Tsit5", "Heun, "Midpoint"
  
  # Density field scaling options
  density_scaling: "none"  # Options: "none", "log", "sqrt", "normalize", "standardize", "power"
  #scaling_kwargs:
    #log_offset: 1.0e-8  # Offset for log scaling
  
  # Blob parameters - a list of blob configurations
  blobs_params:
    # Blob 1: Gaussian with circular velocities
      - n_part: 2000
        m_part: 1.0  # Particle mass
        pos_type: gaussian
        pos_params:
          sigma: 3.0
          center: [29.0, 29.0, 29.0]
        vel_type: circular
        vel_params:
          vel_factor: 0.2
          distrib: true
        

      - n_part: 2000
        m_part: 2.0  # Particle mass
        pos_type: gaussian
        pos_params:
          sigma: 6.0
          center: [37.0, 37.0, 37.0]
        vel_type: circular
        vel_params:
          vel_factor: 0.2
          distrib: true

# --- SAMPLER SETTINGS ---
sampler: nuts           # Options: "hmc" or "nuts"
num_samples: 15000        # Number of MCMC samples to draw
sampling_seed: 12345    # Random seed for reproducibility
num_chains: 7        # Number of chains to run in parallel
# For NUTS:
num_warmup: 1000      # Number of warmup steps 

# Initial position for the sampler - start with values different from the true ones
initial_position: 
  - blob0_sigma: 7.0
    blob0_center: [28.0, 28.0, 28.0]
    blob1_sigma: 6.0           
    blob1_center: [37.0, 37.0, 37.0]
  - blob0_sigma: 5.0
    blob0_center: [25.0, 25.0, 25.0]
    blob1_sigma: 7.0
    blob1_center: [40.0, 40.0, 40.0]
  - blob0_sigma: 4.5
    blob0_center: [26.0, 26.0, 26.0]
    blob1_sigma: 6.5
    blob1_center: [38.0, 38.0, 38.0]
  - blob0_sigma: 6.0
    blob0_center: [27.0, 27.0, 27.0]
    blob1_sigma: 5.5
    blob1_center: [36.0, 36.0, 36.0]
  - blob0_sigma: 3.5
    blob0_center: [28.0, 28.0, 28.0]
    blob1_sigma: 6.0
    blob1_center: [37.0, 37.0, 37.0]
  - blob0_sigma: 4.0
    blob0_center: [29.0, 29.0, 29.0]
    blob1_sigma: 7.5
    blob1_center: [39.0, 39.0, 39.0]
  - blob0_sigma: 5.5
    blob0_center: [30.0, 30.0, 30.0]
    blob1_sigma: 6.5
    blob1_center: [35.0, 35.0, 35.0]
  - blob0_sigma: 4.8
    blob0_center: [31.0, 31.0, 31.0]
    blob1_sigma: 5.8
    blob1_center: [34.0, 34.0, 34.0]
  

# --- LIKELIHOOD SETTINGS ---
likelihood_type: ll1   # Options: "ll1", "ll2"
likelihood_kwargs: 
  noise: 1.0  # Standard deviation of instrumental noise

# --- PRIOR SETTINGS ---
prior_type: blob_uniform
prior_params:
  # Uniform priors for blob 0 parameters
  blob0_sigma: {low: 2.0, high: 6.0}
  blob0_center: {low: [20.0, 20.0, 20.0], high: [34.0, 34.0, 34.0]}
  #blob0_vel_factor: {low: 0.1, high: 0.5}  # Add velocity factor prior for blob 0
  
  # Uniform priors for blob 1 parameters
  blob1_sigma: {low: 4.0, high: 8.0}
  blob1_center: {low: [30.0, 30.0, 30.0], high: [44.0, 44.0, 44.0]}
  #blob1_vel_factor: {low: 0.1, high: 0.5}  # Add velocity factor prior for blob 1