# Configuration for N-body simulation using blobs model

# --- HARDWARE/CLUSTER SETTINGS ---
cuda_visible_devices: 3  # GPU index to use

# --- EXPERIMENT MODE and MISCELLANEOUS ---
mode: sim      # Experiment mode (options: "sim", "sampling")

# --- VIDEO SETTINGS ---
generate_video: false     # Generate simulation video
video_fps: 30            # Video frames per second
video_dpi: 200           # Video resolution DPI

# --- PLOT SETTINGS ---
num_trajectories: 10     # Number of particle trajectories to plot
zoom_for_trajectories: true  # Zoom in on trajectories
plot_timesteps: 8        # Number of timesteps to plot
enable_energy_tracking: true  # Calculate and plot energy evolution

# --- FORWARD MODEL PARAMETERS ---
model_params:  
  # General parameters
  G: 5.0              # Gravitational constant
  length: 64          # Box size
  softening: 0.1      # Softening length
  t_f: 5.0            # Final time
  dt: 0.01            # Time step
  m_part: 1.0         # Particle mass
  data_seed: 42       # Random seed for data generation
  
  # Density field scaling options
  density_scaling: "log"  # Options: "none", "log", "sqrt", "normalize", "standardize", "power"
  scaling_kwargs:
    log_offset: 1.0e-8  # Offset for log scaling
  
  # Blob parameters - a list of blob configurations
  blobs_params:
    # Blob 1: Gaussian with circular velocities
      - n_part: 1000
        pos_type: gaussian
        pos_params:
          sigma: 8.0
          center: [12.0, 52.0, 12.0]s
        vel_type: circular
        vel_params:
          vel_factor: 1.0  # Multiplier for circular velocity
          distrib: False # Use circular velocity distribution or proxy

      # Blob 2: NFW with virial velocities
      - n_part: 1000
        pos_type: nfw
        pos_params:
          rs: 5.0          # Scale radius
          c: 2.0           # Concentration parameter
          center: [12.0, 12.0, 52.0]
        vel_type: virial
        vel_params:
          virial_ratio: 0.5  # Sub-virial (cold) initial condition

      # Blob 3: Gaussian with cold velocities
      - n_part: 1000
        pos_type: gaussian
        pos_params:
          sigma: 6.0
          center: [52.0, 12.0, 12.0]
        vel_type: cold
        vel_params:
          vel_dispersion: 0.1  # Small random velocities

