# Configuration for gradient sanity check

# Use with: python test/gradient_sanity_check.py --config configs/gradient_sanity_check.yaml

cuda_visible_devices: 5

# --- FORWARD MODEL PARAMETERS ---
model_params:  
  # General parameters
  G: 10.0              # Gravitational constant
  length: 64          # Box size
  softening: 1      # Softening length
  t_f: 0.35            # Final time
  dt: 0.01            # Time step
  m_part: 1.0         # Particle mass
  data_seed: 42       # Random seed for data generation
  solver: "Tsit5" # Solver type: "LeapfrogMidpoint", "Dopri5", "Dopri8", "Tsit5", "Heun, "Midpoint"
  
  # Density field scaling options
  density_scaling: "none"  # Options: "none", "log", "sqrt", "normalize", "standardize", "power"
  #scaling_kwargs:
    #log_offset: 1.0e-8  # Offset for log scaling
  
  # Blob parameters - a list of blob configurations
  blobs_params:
    # Blob 1: Gaussian with circular velocities
      - n_part: 2000
        pos_type: gaussian
        pos_params:
          sigma: 5.0
          center: [29.0, 29.0, 29.0]
        vel_type: circular
        vel_params:
          vel_factor: 0.2
          distrib: true
        

      - n_part: 2000
        pos_type: gaussian
        pos_params:
          sigma: 5.0
          center: [37.0, 37.0, 37.0]
        vel_type: circular
        vel_params:
          vel_factor: 0.2
          distrib: true


# --- HYPERCUBE PARAMETERS ---
hypercube_params:
  n_points_per_dim: 8  # Number of points per parameter dimension (5^n_params total evaluations)
  mini_batch_size: 75  # Size of mini-batches for gradient evaluation (fallback when full batch fails)
  
  # Parameter bounds for the hypercube
  param_bounds:
    blob0_sigma: 
      min: 2.0
      max: 15.0
    blob0_center:
      min: 25.0  # Scalar value applied to all three coordinates
      max: 40.0
    blob1_sigma: 
      min: 2.0
      max: 15.0
    blob1_center:
      min: 25.0  # Scalar value applied to all three coordinates
      max: 40.0
    

# --- LIKELIHOOD SETTINGS ---
likelihood_type: ll1   # Use deterministic likelihood for gradient checking
likelihood_kwargs: 
  noise: 1.0  # Standard deviation of instrumental noise

# --- PRIOR SETTINGS ---
prior_type: blob_gaussian  # Use blob-specific prior
prior_params:
  # Priors for the parameters we want to check
  blob0_sigma: {mu: 5.0, sigma: 3.0}
  blob0_center: {mu: [29.0, 29.0, 29.0], sigma: 2.0}
  blob1_sigma: {mu: 5.0, sigma: 3.0}
  blob1_center: {mu: [36.0, 36.0, 36.0], sigma: 2.0}
