# Quick performance test configuration

cuda_visible_devices: 6

performance_params:
  t_f: 0.05
  dt: 0.01
  G: 5.0
  softening: 0.1
  length: 32
  n_part_range: [500, 1000, 1500, 2000]

methods_to_test:
  jax_experimental_ode: false  # Skip for quick test
  jax_diffrax_nojit: true
  jax_diffrax_jit: true
  jax_diffrax_flat_nojit: false  # Skip for quick test
  jax_diffrax_flat_jit: false   # Skip for quick test

output_settings:
  create_linear_plot: true
  create_log_plot: true
  create_speedup_plot: true
  create_success_plot: true
  save_raw_data: true
  save_summary_report: true

analysis_params:
  compute_scaling_analysis: true
  compute_efficiency_metrics: true
  generate_recommendations: true